version: '3.5'

services:

  discovery-server:
    image: "discovery-server"
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  movie-catalog-service:
    image: "move-catalog-service"
    build:
      context: ./movie-catalog-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server

  movie-info-service:
    image: "movie-info-service"
    build:
      context: ./movie-info-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - movie-catalog-service

  ratings-data-service:
    image: "rating-data-service"
    build:
      context: ./ratings-data-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - movie-info-service

  spring-boot-admin:
    image: "spring-boot-admin"
    build:
      context: ./spring-boot-admin
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
