version: '3.5'

services:

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    stdin_open: true

  movie-catalog-service:
    build:
      context: ./movie-catalog-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    stdin_open: true
    depends_on:
      - discovery-server

  movie-info-service:
    build:
      context: ./movie-info-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    stdin_open: true
    depends_on:
      - movie-catalog-service

  ratings-data-service:
    build:
      context: ./ratings-data-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    stdin_open: true
    depends_on:
      - movie-info-service
